### ISSUE TITLE
If you want to show the alert on a different page, opened from a base page, then the pop-ups are not shown

### ISSUE THREAD

**Issue by psmits1567** [gustavosmanc/cute-alert#10]
It would be great if that could be implemented as a parameter.
I solved it by adding a parameter, and added the myWindow parameter to the document statements
function cuteAlert({
  type,
  title,
  message,
  buttonText = "OK",
  confirmText = "OK",
  cancelText = "Cancel",
  myWindow ="",
  closeStyle,
}) {

const scripts = myWindow.document.getElementsByTagName("script");

**Comment by gustavosmanc** [comment]
Hey @psmits1567, thanks for the feedback but I'm noo sure if I understand. The expected behavior of the library is that you call its function on the place you expect it to pop-up.

Nonetheless, I'm working on a [PR](https://github.com/gustavosmanc/cute-alert/pull/30) in which I plan to bring a lot of improvements to the library such as add it to npm, typescript declarations, improve how the pop-ups are open, etc. I will also add a better documentation and a storybook so people are able to check the alerts / toasts out before implementing it.

Having that said, I'll be closing this issue for now and you can try it out again once the update hits.
