### ISSUE TITLE
Uncaught (in promise) ReferenceError: img is not defined

### ISSUE THREAD

**Issue by Calabashmc** [gustavosmanc/cute-alert#20]
As the title says I get an error trying to display a Toast - Uncaught (in promise) ReferenceError: img is not defined
line 152 of cute-alert.js
        ${img !== '' ? '<div class="alert-header ' + type + '-bg">' : '<div>'}

CuteAlert works but doesn't display the icon. 
My directory structure is:

app/static/cute-alert/img/image files here
js and css are in app/static/cute-alert/

I'm new to javascript so don't know how to troubleshoot this.

**Comment by aderowbotham** [comment]
I have exactly this problem. I don't understand why the image is not being created from `src` and `type`.svg
It seems like img can be passed as an object property but if it's not then you get a 404 for: `libraries/cute-alert/undefined`

This makes sense since the code checks strictly if `img !== ''` but the value of img is `undefined`

**Comment by odutra-dev** [comment]
`img` gets the path of the image you want to display.

**Comment by gustavosmanc** [comment]
Hey folks, I'm working on [this PR](https://github.com/gustavosmanc/cute-alert/pull/30), in which I plan to improve how images are handled overall. I'll take this feedback into account and come up with a fix for it. On this new version, it should be easier for you to include your own images as well :-)
