### ISSUE TITLE
Undefined variable 'url' in line number 215

### ISSUE THREAD

**Issue by thesharifdev** [gustavosmanc/cute-alert#31]
Hi,

As you checking the the 'url' variable in the 215 no line (please see the attached image). It's actually undefined and in the same scope has na url variable so it's showing a console error.
![error](https://github.com/gustavosmanc/cute-alert/assets/59281214/57b8e527-8bab-4925-9ab9-700e1e001874)

Thank you

**Comment by gustavosmanc** [comment]
Hey @thesharifdev, can you send me a reproducible example or an screenshot with the error? Nonetheless, I'm working on a [PR](https://github.com/gustavosmanc/cute-alert/pull/30) in which I'm doing a complete refactor on the library and also how it handles images, so in case it's an actual issue, it should be fixed in the next version.

**Comment by thesharifdev** [comment]
Sure, @gustavosmanc :),

Here it is:
![cutealert](https://github.com/gustavosmanc/cute-alert/assets/59281214/cfa1913e-8a92-4026-83a8-666250c661d3)

Thanks
Sharif

**Comment by blv-gustavomancuzo** [comment]
Got it @thesharifdev, thanks for reporting it :-). This is already fixed in the PR I'm working on, for the time being, you can just remove the following lines of code from the file:

<img width="745" alt="Captura de pantalla 2024-02-25 a la(s) 14 29 52" src="https://github.com/gustavosmanc/cute-alert/assets/96124963/42929d12-2400-44fb-962a-19c305bb79b8">

**Comment by gustavosmanc** [comment]
Got it @thesharifdev, this is already fixed in the PR I'm working on. For the time being you can just remove the following line of codes from the file:

<img width="745" alt="Captura de pantalla 2024-02-25 a la(s) 14 29 52" src="https://github.com/gustavosmanc/cute-alert/assets/25268505/a14e57e5-48f0-4b0a-80cb-17508d4c6d09">

I'll be closing the issue, thanks for reporting it :-)

**Comment by thesharifdev** [comment]
Great @gustavosmanc 🙂

Thank you
